apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudpulse.fullname" . }}-config
  labels:
    {{- include "cloudpulse.labels" . | nindent 4 }}
data:
  EPHEMERAL_MODE: {{ .Values.ephemeralMode | quote }}
  DEFAULT_CURRENCY: {{ .Values.currency | quote }}
  USD_TO_INR_RATE: {{ .Values.exchangeRate | quote }}
  AWS_DEFAULT_REGION: {{ .Values.awsRegion | quote }}
  FINOPS_READ_ONLY: {{ .Values.aws.readOnlyMode | quote }}
  GITOPS_ENABLE_PRS: {{ .Values.aws.enableRemediationPRs | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  FOCUS_LAKEHOUSE_ENGINE: {{ .Values.env.FOCUS_LAKEHOUSE_ENGINE | quote }}
  AUTONOMOUS_MODE: {{ .Values.env.AUTONOMOUS_MODE | quote }}
  OPENCOST_API_URL: {{ .Values.env.OPENCOST_API_URL | quote }}
